### ISSUE TITLE
E-mail?

### ISSUE THREAD

**Issue by Harchvertelol** [mattbruv/project-euler#1]
I'm very sorry about this post. Github don't have private messages, so I have to write here. I read your excellent article about fixing a mistake in a shockwave game, I would like to ask a few questions on this topic. If not difficult, please give your email. Thank you!

**Comment by mattbruv** [comment]
Thanks! No problem. I'd prefer not to publicly post my e-mail, so feel free to add me on discord and send me a message at mp#8248 or if you're fine with posting your email I can reach out to you.

**Comment by Harchvertelol** [comment]
Unfortunately, I could not find you in the discord with mp#8248. My discord is "Harch#2071". I would be grateful if you write to me. Thank you!
